
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "10b98e0afdba4c3c57d3a519887fddfdba6ca161",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
